# Constants
SKILL_NAME = "Kreeda Stats"
WELCOME_MESSAGE = "Welcome to Kreeda Stats."
HELP_MESSAGE = "You can say give me top running back week 10 2015, or, you can say exit... What can I help you with?"
HELP_REPROMPT = "What can Kreeda help you with?"
STOP_MESSAGE = "Out and over!"
ASK_MESSAGE = "Anything else I can help you with?"
FALLBACK_MESSAGE = "Sorry I did not understand that! What can I help you with?"
FALLBACK_REPROMPT = 'What can I help you with?'
EXCEPTION_MESSAGE = "Sorry. I cannot help you with that."
FAIL_INSIDE_INTENT_MESSAGE = "Sorry Kreeda did not understand!"
RB_RESP_SENTENCE_BEGIN = "Here is the top running back for"
QB_RESP_SENTENCE_BEGIN = "Here is the top quarter back for"
WR_RESP_SENTENCE_BEGIN = "The top receiver for"
NFL_DID_NOT_EXIST_THEN_MESSAGE = "NFL did not even exist then? Don't act smart now!"
FUTURE_YEAR_MESSAGE = "I'm no prophet to see the future!"
NFL_STATS_DONT_EXIST_MESSAGE = "I don't have those stats. I only have stats from 1999 season to the current year!"
RB_CARD_TITLE = 'Top Running Back'
QB_CARD_TITLE = 'Top Quarter Back'
WR_CARD_TITLE = 'Top Wide Receiver'
TOP_N = 1